#!/bin/sh
set -e 

if [ $# -lt 1 ]; then
    >&2 echo "Usage: $(basename $0) <repo e.g. spritsail/test>"
    exit 1
fi

REPO="$1"

{ pass drone.spritsail.io/env; echo; } | \
    while read secret; do
        name="$(echo ${secret%%:*} | xargs)"
        value="$(echo ${secret#*:} | xargs)"
        drone secret add --name="$name" --value="$value" "$REPO"
    done


MICROBADGER_API="https://api.microbadger.com/v1/images"
MICROBADGER_TOKEN="$(curl -sSL "$MICROBADGER_API/$REPO" | jq -r .WebhookURL | sed 's|^.*/||g')"

if [ -n "$MICROBADGER_TOKEN" ]; then
    drone secret add --name=microbadger_token --value="$MICROBADGER_TOKEN" "$REPO"
fi
